In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
df = pd.read_excel ('./RelatorioQualidadeAguasSuperficiais.xlsx')
df.head()

,Período DE,Período ATE,Cod_Interaguas,Tipo Rede,UGRHI,Código Ponto,Status Ponto,Data Coleta,Hora Coleta,Parametro,...,CLASSE,Município,UF,Inicio Operação,Fim Operação,Latitude,Longitude,Altitude,Localização,Captação
0,01/01/2016,01/01/2021,136,Rede Básica,06 - ALTO TIÊTE,PINH04100,Ativo,28/01/2016,11:18,pH,...,Classe 4,SÃO PAULO,SP,01/01/1977,NaN,23 42 09,46 40 26,774,"Na Usina Elevatória de Pedreira, no centro do ...",N
1,01/01/2016,01/01/2021,136,Rede Básica,06 - ALTO TIÊTE,PINH04100,Ativo,30/03/2016,11:45,pH,...,Classe 4,SÃO PAULO,SP,01/01/1977,NaN,23 42 09,46 40 26,774,"Na Usina Elevatória de Pedreira, no centro do ...",N
2,01/01/2016,01/01/2021,136,Rede Básica,06 - ALTO TIÊTE,PINH04100,Ativo,19/05/2016,12:01,pH,...,Classe 4,SÃO PAULO,SP,01/01/1977,NaN,23 42 09,46 40 26,774,"Na Usina Elevatória de Pedreira, no centro do ...",N
3,01/01/2016,01/01/2021,136,Rede Básica,06 - ALTO TIÊTE,PINH04100,Ativo,13/07/2016,12:30,pH,...,Classe 4,SÃO PAULO,SP,01/01/1977,NaN,23 42 09,46 40 26,774,"Na Usina Elevatória de Pedreira, no centro do ...",N
4,01/01/2016,01/01/2021,136,Rede Básica,06 - ALTO TIÊTE,PINH04100,Ativo,14/09/2016,12:00,pH,...,Classe 4,SÃO PAULO,SP,01/01/1977,NaN,23 42 09,46 40 26,774,"Na Usina Elevatória de Pedreira, no centro do ...",N